# Generated by Django 2.0.2 on 2018-10-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20181002_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
