# Generated by Django 2.0.2 on 2018-10-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20181003_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='type',
            field=models.CharField(default='Not Specified', max_length=40),
        ),
    ]
